# Generated by Django 5.2.13 on 2026-04-10 16:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bitrix24Portal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(db_index=True, help_text='Unique portal identifier from Bitrix24.', max_length=64, unique=True)),
                ('domain', models.CharField(help_text='Portal domain, e.g. company.bitrix24.ru', max_length=255)),
                ('access_token', models.CharField(max_length=512)),
                ('refresh_token', models.CharField(max_length=512)),
                ('access_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('app_status', models.CharField(blank=True, help_text='L=local, F=free, D=demo, T=trial, P=paid', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('installed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-installed_at'],
            },
        ),
    ]
