# Generated by Django 5.0.8 on 2026-02-24 05:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AmoLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amo_lead_id', models.BigIntegerField(unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pipeline_id', models.BigIntegerField(blank=True, null=True)),
                ('status_id', models.BigIntegerField(blank=True, null=True)),
                ('responsible_user_id', models.BigIntegerField(blank=True, null=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('is_success', models.BooleanField(default=False)),
                ('amo_created_at', models.DateTimeField(blank=True, null=True)),
                ('amo_updated_at', models.DateTimeField(blank=True, null=True)),
                ('first_received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_webhook_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-first_received_at', '-amo_lead_id'],
            },
        ),
        migrations.CreateModel(
            name='DealSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amo_deal_id', models.BigIntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('responsible_user_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AmoManagerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amo_user_id', models.BigIntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('max_active_deals', models.PositiveIntegerField(default=10)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('django_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amo_manager_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', 'amo_user_id'],
            },
        ),
        migrations.CreateModel(
            name='AmoLeadAssignmentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_responsible_user_id', models.BigIntegerField(blank=True, null=True)),
                ('new_responsible_user_id', models.BigIntegerField(blank=True, null=True)),
                ('reason', models.CharField(default='auto_assignment', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amo_lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_events', to='crm.amolead')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.amomanagerprofile')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='amolead',
            name='assigned_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='crm.amomanagerprofile'),
        ),
        migrations.CreateModel(
            name='CallAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_id', models.CharField(db_index=True, max_length=128)),
                ('transcript', models.TextField(blank=True)),
                ('analysis', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='call_analyses', to='crm.dealsnapshot')),
            ],
        ),
        migrations.CreateModel(
            name='ManagerDayOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days_off', to='crm.amomanagerprofile')),
            ],
            options={
                'ordering': ['-date', 'manager__name'],
                'unique_together': {('manager', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ManagerWeekdaySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Пн'), (1, 'Вт'), (2, 'Ср'), (3, 'Чт'), (4, 'Пт'), (5, 'Сб'), (6, 'Вс')])),
                ('is_working', models.BooleanField(default=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekday_schedules', to='crm.amomanagerprofile')),
            ],
            options={
                'ordering': ['manager_id', 'weekday'],
                'unique_together': {('manager', 'weekday')},
            },
        ),
    ]
