# Generated by Django 5.0.8 on 2026-02-25 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleFormReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_id', models.BigIntegerField(db_index=True)),
                ('form_type', models.CharField(choices=[('menu', 'menu'), ('cruise', 'cruise')], max_length=16)),
                ('language', models.CharField(choices=[('ru', 'ru'), ('en', 'en')], max_length=2)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('file', models.FileField(upload_to='menus/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['lead_id', 'form_type', 'language', '-created_at'], name='crm_googlef_lead_id_e5b589_idx')],
            },
        ),
    ]
