# Generated by Django 5.0.8 on 2026-02-25 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_googleformreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='callanalysis',
            name='ai_provider',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='callanalysis',
            name='audio_file',
            field=models.FileField(blank=True, upload_to='calls/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='callanalysis',
            name='audio_source_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='callanalysis',
            name='processing_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='callanalysis',
            name='raw_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='callanalysis',
            name='stt_provider',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='callanalysis',
            name='transcript_segments',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='callanalysis',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
