# Generated by Django 5.0.8 on 2026-02-26 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_callanalysis_ai_provider_callanalysis_audio_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amomanagerprofile',
            name='is_service_active',
            field=models.BooleanField(default=True),
        ),
    ]
