# Generated by Codex on 2026-02-26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0004_amomanagerprofile_is_service_active"),
    ]

    operations = [
        migrations.RenameField(
            model_name="amomanagerprofile",
            old_name="is_active",
            new_name="is_amo_active",
        ),
        migrations.RenameField(
            model_name="amomanagerprofile",
            old_name="is_service_active",
            new_name="is_active",
        ),
    ]
